# Generated by Django 5.0.1 on 2024-01-15 17:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1 year.'), django.core.validators.MaxValueValidator(120, message='Age cannot exceed 120 years.')])),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='invalid_phone_number', regex='^\\d{10}$')])),
                ('monthly_salary', models.PositiveIntegerField()),
                ('approved_limit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tenure', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_repayment', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('emis_paid_on_time', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.customerdata')),
            ],
        ),
    ]
